#!/bin/bash
# Test Message Delivery Between Freelancer and Client

echo "🧪 TESTING MESSAGE DELIVERY: CLIENT ↔ FREELANCER"
echo "================================================="
echo ""

echo "📊 Database Check"
echo "-----------------"
echo "Messages between user 13 and 14:"
mysql -u root worklab -e "
SELECT 
  id, 
  senderId, 
  receiverId, 
  LEFT(content, 40) as content,
  messageType,
  createdAt 
FROM Messages 
WHERE (senderId = 13 AND receiverId = 14) 
   OR (senderId = 14 AND receiverId = 13)
ORDER BY createdAt DESC 
LIMIT 10;
"

echo ""
echo "🧪 TEST INSTRUCTIONS"
echo "===================="
echo ""
echo "TEST 1: Client (User 14) sends message to Freelancer (User 13)"
echo "----------------------------------------------------------------"
echo "Setup:"
echo "  1. Browser Window 1: Login as FREELANCER (User 13)"
echo "  2. Open /messages route"
echo "  3. Open DevTools Console (F12)"
echo "  4. Browser Window 2: Login as CLIENT (User 14)"
echo "  5. Open /clientmessages route"
echo "  6. Select conversation with User 13"
echo ""
echo "Action:"
echo "  7. Client sends message: 'Test from client'"
echo ""
echo "Expected Results:"
echo "  ✅ Backend terminal shows:"
echo "     - '🔵 sendMessage called - receiverId: 13 senderId: 14'"
echo "     - '✅ Message broadcasted successfully to conversation:13:14'"
echo "     - '🔔 Sending notification to channel: user:13'"
echo "     - '✅ Notification successfully sent to user:13'"
echo ""
echo "  ✅ Freelancer's browser console shows:"
echo "     - '🔔 Notification received: ...'"
echo "     - '💬 Processing message notification'"
echo "     - '✅ Message notification toast added'"
echo ""
echo "  ✅ Freelancer sees:"
echo "     - Toast notification: 'New Message from FirstName'"
echo "     - If on /messages with conversation open: Message appears instantly"
echo ""

echo "TEST 2: Freelancer (User 13) sends message to Client (User 14)"
echo "----------------------------------------------------------------"
echo "Setup:"
echo "  1. Keep both browser windows open from TEST 1"
echo "  2. Freelancer on /messages"
echo "  3. Client on /clientmessages"
echo ""
echo "Action:"
echo "  4. Freelancer sends message: 'Test from freelancer'"
echo ""
echo "Expected Results:"
echo "  ✅ Backend terminal shows:"
echo "     - '🔵 sendMessage called - receiverId: 14 senderId: 13'"
echo "     - '✅ Message broadcasted successfully to conversation:13:14'"
echo "     - '🔔 Sending notification to channel: user:14'"
echo "     - '✅ Notification successfully sent to user:14'"
echo ""
echo "  ✅ Client's browser console shows:"
echo "     - '🔔 Notification received: ...'"
echo "     - '💬 Processing message notification'"
echo "     - '✅ Message notification toast added'"
echo ""
echo "  ✅ Client sees:"
echo "     - Toast notification: 'New Message from FirstName'"
echo "     - If on /clientmessages with conversation open: Message appears instantly"
echo ""

echo "TEST 3: Receiver NOT on messages page"
echo "--------------------------------------"
echo "Setup:"
echo "  1. Browser Window 1: Freelancer on /jobs (NOT /messages)"
echo "  2. DevTools Console open"
echo "  3. Browser Window 2: Client on /clientmessages"
echo ""
echo "Action:"
echo "  4. Client sends message"
echo ""
echo "Expected Results:"
echo "  ✅ Freelancer's console shows notification received"
echo "  ✅ Toast notification appears"
echo "  ✅ Click 'View Messages' → navigates to /messages"
echo "  ✅ Message appears in conversation"
echo ""

echo "🔍 DEBUGGING CHECKLIST"
echo "======================"
echo ""
echo "If messages not appearing, check:"
echo ""
echo "1. Backend Logs:"
echo "   [ ] '🔵 sendMessage called'"
echo "   [ ] '✅ Message broadcasted successfully'"
echo "   [ ] '🔔 Sending notification to channel: user:X'"
echo "   [ ] '✅ Notification successfully sent to user:X'"
echo ""
echo "2. Frontend Console (Receiver):"
echo "   [ ] '✅ Connected to Centrifugo'"
echo "   [ ] '🔔 Setting up real-time notifications for user: X'"
echo "   [ ] '✅ Subscribed to user notifications: user:X'"
echo "   [ ] '🔔 Notification received: ...'"
echo "   [ ] '💬 Processing message notification'"
echo ""
echo "3. Database:"
echo "   [ ] Message saved in Messages table"
echo "   [ ] Conversation updated in Conversations table"
echo ""
echo "4. Environment:"
echo "   [ ] Centrifugo container running"
echo "   [ ] VITE_CENTRIFUGO_ENABLED=true in frontend/.env"
echo "   [ ] Backend on port 3000"
echo "   [ ] Frontend on port 5173"
echo ""

echo "🎯 Quick Database Query"
echo "========================"
echo "Run this after sending a message:"
echo ""
echo "mysql -u root worklab -e \"SELECT id, senderId, receiverId, content, createdAt FROM Messages ORDER BY createdAt DESC LIMIT 1;\""
echo ""
echo "Should show the message you just sent."
