#!/bin/bash
# Comprehensive Message & Notification Test

echo "🧪 COMPREHENSIVE MESSAGE & NOTIFICATION TEST"
echo "=============================================="
echo ""

echo "📊 Step 1: Check Database Status"
echo "---------------------------------"
echo "Total messages in database:"
mysql -u root worklab -e "SELECT COUNT(*) as total FROM Messages;"

echo ""
echo "Latest 3 messages:"
mysql -u root worklab -e "SELECT id, senderId, receiverId, LEFT(content, 30) as content, messageType, createdAt FROM Messages ORDER BY createdAt DESC LIMIT 3;"

echo ""
echo "📊 Step 2: Check Conversations"
echo "-------------------------------"
mysql -u root worklab -e "SELECT id, participant1Id, participant2Id, lastMessageId, lastMessageAt, unreadCount1, unreadCount2 FROM Conversations ORDER BY lastMessageAt DESC LIMIT 3;"

echo ""
echo "🧪 Step 3: MANUAL TEST - Real-time Notifications"
echo "------------------------------------------------"
echo ""
echo "TEST A: Receiver is ONLINE (User 14 logged in)"
echo "   1. Open browser 1: Login as USER 14 (receiver)"
echo "   2. Open browser console (F12)"
echo "   3. Keep console open to see logs"
echo "   4. Open browser 2: Login as USER 13 (sender)"
echo "   5. Send a message to USER 14"
echo ""
echo "   ✅ EXPECTED in User 14's console:"
echo "      - '🔔 Notification received: ...'"
echo "      - '🔔 Notification type: message_notification'"
echo "      - Toast notification appears"
echo ""
echo "   ✅ EXPECTED in backend terminal:"
echo "      - '🔵 sendMessage called - receiverId: 14 senderId: 13'"
echo "      - '✅ Message broadcasted successfully to conversation:13:14'"
echo "      - '🔔 Notification sent to user:14'"
echo ""

echo "TEST B: Receiver is NOT on /messages page"
echo "   1. User 14: Navigate to /jobs page (NOT /messages)"
echo "   2. Keep console open"
echo "   3. User 13: Send another message"
echo ""
echo "   ✅ EXPECTED:"
echo "      - User 14 still sees toast notification (RealTimeNotifications is global)"
echo "      - Console shows notification received"
echo "      - When User 14 goes to /messages, message appears"
echo ""

echo "TEST C: Check Frontend Connection"
echo "   1. User 14: Open console (F12)"
echo "   2. Look for these logs at page load:"
echo "      - '✅ Connected to Centrifugo'"
echo "      - '🔔 Setting up real-time notifications for user: 14'"
echo "      - '✅ Subscribed to user notifications: user:14'"
echo ""
echo "   ❌ If you see these instead:"
echo "      - '⚠️ Centrifugo disabled via VITE_CENTRIFUGO_ENABLED'"
echo "      - '❌ Failed to connect to Centrifugo'"
echo "      → Check .env file: VITE_CENTRIFUGO_ENABLED=true"
echo ""

echo "📊 Step 4: Check Environment Variables"
echo "--------------------------------------"
echo "Backend .env (Centrifugo config):"
grep -E "CENTRIFUGO" /Users/prajwalgaire/worklab/.env 2>/dev/null || echo "⚠️ .env file not found"

echo ""
echo "Frontend .env (Centrifugo config):"
grep -E "CENTRIFUGO" /Users/prajwalgaire/worklab/frontend/.env 2>/dev/null || echo "⚠️ frontend/.env not found"

echo ""
echo "📊 Step 5: Check if Centrifugo is Running"
echo "-----------------------------------------"
if docker ps | grep -q centrifugo; then
    echo "✅ Centrifugo container is running"
    docker ps | grep centrifugo
else
    echo "❌ Centrifugo container NOT running!"
    echo "   Start it with: ./start-centrifugo.sh"
fi

echo ""
echo "🎯 SUMMARY: What Should Happen"
echo "================================"
echo "When User 13 sends a message to User 14:"
echo ""
echo "1. ✅ Message saved to Messages table (confirmed - 133 messages exist)"
echo "2. ✅ Conversation updated in Conversations table"
echo "3. ✅ Backend broadcasts to conversation:13:14 channel"
echo "4. ✅ Backend sends notification to user:14 channel"
echo "5. ✅ If User 14 is online:"
echo "      - RealTimeNotifications component receives it"
echo "      - Toast notification appears"
echo "      - Console shows logs"
echo "6. ✅ If User 14 is offline:"
echo "      - No toast (normal)"
echo "      - Message saved in DB"
echo "      - Appears when User 14 opens /messages"
echo ""
echo "🔍 DEBUGGING CHECKLIST:"
echo "======================="
echo "[ ] Centrifugo container running (docker ps | grep centrifugo)"
echo "[ ] Backend .env has CENTRIFUGO_URL and CENTRIFUGO_API_KEY"
echo "[ ] Frontend .env has VITE_CENTRIFUGO_ENABLED=true"
echo "[ ] Frontend .env has VITE_CENTRIFUGO_URL=ws://localhost:8000/connection/websocket"
echo "[ ] User is logged in"
echo "[ ] Browser console shows '✅ Connected to Centrifugo'"
echo "[ ] Browser console shows '✅ Subscribed to user notifications: user:X'"
echo "[ ] Backend terminal shows '🔔 Notification sent to user:X'"
echo ""
echo "Run this test, then let me know:"
echo "1. Do you see the logs in the console?"
echo "2. Does the toast appear?"
echo "3. Are messages showing in the database?"
